[workspace]
resolver = "2"
members = ["crates/calc", "crates/lang", "crates/modus"]

[workspace.dependencies]
lome-modus = { version = "0.1.0", path = "crates/modus" }
lome-calc = { version = "0.1.0", path = "crates/calc" }
lome-lang = { version = "0.1.0", path = "crates/lang" }

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "BSD-3-Clause"
authors = ["Hans S. <hans@0x8.io>"]
description = "Lome: Pure Type System implemented as Lambda-Typed-Lambda-Calculus implemented as Call-by-Value Pattern Calculus with Pattern-Enforced-Equality"
repository = "https://github.com/DaBigBlob/lome"
readme = "README.md"

# --release
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = 0
debug-assertions = false
overflow-checks = false
incremental = false

# --profile small
[profile.small]
inherits = "release"
opt-level = "z"
