[package]
name = "lome-calc"
description = "Lome Core Calculus: Call-by-Value Pattern Calculus with Pattern-Enforced-Equality"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
lome-modus = { workspace = true }
hashbrown = { version = "0.17.1", default-features = false, features = ["default-hasher", "inline-more"] }
